name: Continuous delivery

on:
  workflow_run:
    workflows: [Continuous integration]
    types: [completed]
    branches: [main]

env:
  REGION: us-central1
  PROJECT: challenge-443802
  REPO: main
  IMAGE: demo-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Vars
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE" >> $GITHUB_ENV

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.IMAGE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.IMAGE_TAG }}'

      - name: Show output
        run: echo ${{ steps.deploy.outputs.url }}

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: create venv
        run: make venv
      - name: install dependencies
        run: make install
      - name: test api
        run: make api-test
      - name: stress api
        run: make stress-test